
x-defaults:
  &defaults
  init: true
  tty: true
  networks:
    - gamdom_network

services:
  postgres:
    <<: *defaults
    image: postgres:16-alpine3.20
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./db_data/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # api:
  #   <<: *defaults
  #   depends_on:
  #     - postgres
  #   container_name: gamdom_api
  #   build: 
  #     dockerfile: ./Dockerfile
  #     context: ./../
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
    
volumes:
  db:
    driver: local

networks:
  gamdom_network: